### ISSUE TITLE
GLES20RecordingCanvas 

### ISSUE THREAD

**Issue by ntsparis** [Ramotion/folding-cell-android#38]
I run the latest update avilable on github repo of folding-cell-listview-example in Api 15, Android 4.0.4 and i get this error:
01-13 15:00:33.467 4646-4646/com.ramotion.foldingcell.examples.listview E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                          java.lang.NullPointerException
                                                                                              at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:118)
                                                                                              at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:393)
                                                                                              at android.widget.ImageView.onDraw(ImageView.java:892)
                                                                                              at android.view.View.draw(View.java:10978)
                                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:2887)
                                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:2885)
                                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                              at android.view.View.getDisplayList(View.java:10415)
                                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                              at android.view.View.getDisplayList(View.java:10415)
                                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                              at android.widget.ListView.drawChild(ListView.java:3223)
                                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                              at android.widget.AbsListView.dispatchDraw(AbsListView.java:2092)
                                                                                              at android.widget.ListView.dispatchDraw(ListView.java:3218)
                                                                                              at android.view.View.draw(View.java:10981)
                                                                                              at android.widget.AbsListView.draw(AbsListView.java:3398)
                                                                                              at android.view.View.getDisplayList(View.java:10417)
                                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                              at android.view.View.draw(View.java:10981)
                                                                                              at android.widget.FrameLayout.draw(FrameLayout.java:450)
                                                                                              at android.view.View.getDisplayList(View.java:10417)
                                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                              at android.view.View.draw(View.java:10981)
                                                                                              at android.support.v7.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:442)
                                                                                              at android.view.View.getDisplayList(View.java:10417)
                                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                              at android.view.View.getDisplayList(View.java:10415)
                                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                              at android.view.View.getDisplayList(View.java:10415)
                                                                                              at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
                                                                                              at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
                                                                                              at android.view.View.draw(View.java:10981)
                                                                                              at android.widget.FrameLayout.draw(FrameLayout.java:450)
                                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2134)
                                                                                              at android.view.View.getDisplayList(View.java:10417)
                                                                                              at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:875)
                                                                                              at android.view.ViewRootImpl.draw(ViewRootImpl.java:1918)
                                                                                              at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1642)
                                                                                              at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2450)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                              at android.os.Looper.loop(Looper.java:137)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:4444)
                                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                              at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
                                                                                              at dalvik.system.NativeStart.main(Native Method)
01-13 15:00:33.487 309-496/? E/hubo_EventLog: OnException

**Comment by ntsparis** [comment]
Any ideas, anyone?

**Comment by matteofilia** [comment]
The readme says it requires 4.2.2 (API 17) or greater. Are you trying to get it to work below that?

**Comment by oleg-vasiliev** [comment]
Seems like that error occurs on some devices with API lvl 20 and below, due to incorrect work with hardware layer render acceleration. Most likely, error can be fixed by forcing use of software layer acceleration on old devices, but i am not sure.

**Comment by anastr** [comment]
same error on API 15
any solution @oleg-vasiliev @ntsparis  ??
```
java.lang.NullPointerException
         at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:118)
         at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:393)
         at android.widget.ImageView.onDraw(ImageView.java:892)
         .....
```
