### ISSUE TITLE
Gradle 3.0 Alpha 2 throwing exception

### ISSUE THREAD

**Issue by jonashao** [Ramotion/folding-cell-android#48]
When using gradle build tool 3.0.0-alpha2 in Android studio preview
 ```
dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-alpha2'
}
```
I got this error:
```
ERROR: 
...\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:15 unknown element <library> found

Failed to execute aapt
com.android.ide.common.process.ProcessException: Failed to execute aapt
	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:803)
	at com.android.build.gradle.tasks.ProcessAndroidResources.invokeAaptForSplit(ProcessAndroidResources.java:548)
...

Issues:
 - ERROR: C:\Users\Jonas\Projects\Android\Hey\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:15 unknown element <library> found
	at com.android.builder.internal.aapt.v2.AaptV2Jni.buildException(AaptV2Jni.java:136)
	at com.android.builder.internal.aapt.v2.AaptV2Jni.makeValidatedPackage(AaptV2Jni.java:80)
	at com.android.builder.internal.aapt.AbstractAapt.link(AbstractAapt.java:40)
	... 48 more

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt
```

It seems that the library element in `AndroidManifest.xml` has problem in this gradle version.
```
<library
        android:name="@string/app_name"
        android:label="@string/app_name" />
```

**Comment by Vijaykumarj** [comment]
Already i am also faced same issue. please give solution as early as possible.

**Comment by oleg-vasiliev** [comment]
fixed in v.1.2.1
