### ISSUE TITLE
Unfold cell programmatically

### ISSUE THREAD

**Issue by basmasrour** [Ramotion/folding-cell-android#49]
How to unfold or fold cell in specific index of list view programmatically without click on it?
when I called cell.unfold(true) returns NullPointerException: 
   Attempt to write to field 'int android.view.ViewGroup$LayoutParams.height' on a null object reference

when use cell.toggle(false);
                registerToggle(position);
returns FATAL EXCEPTION: main
                                                                        Process:  PID: 30807
                                                                        java.lang.IllegalArgumentException: width and height must be > 0
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:967)
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
                                                                            at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
                                                                            at com.ramotion.foldingcell.FoldingCell.getBitmapFromView(FoldingCell.java:343)
                                                                            at com.ramotion.foldingcell.FoldingCell.unfold(FoldingCell.java:130)
                                                                            at com.ramotion.foldingcell.FoldingCell.toggle(FoldingCell.java:222)

**Comment by oleg-vasiliev** [comment]
will be fixed with #36 in version 1.2.0
