### ISSUE TITLE
i get this error :   java.lang.IllegalStateException: Additional flips count is too small

### ISSUE THREAD

**Issue by sinadalvand** [Ramotion/folding-cell-android#56]
`
                                                                              Process: sinadalvand.a30nama.co.a30nama, PID: 4943
                                                                              java.lang.IllegalStateException: Additional flips count is too small
                                                                                  at com.ramotion.foldingcell.FoldingCell.calculateHeightsForAnimationParts(FoldingCell.java:292)
                                                                                  at com.ramotion.foldingcell.FoldingCell.unfold(FoldingCell.java:134)
                                                                                  at com.ramotion.foldingcell.FoldingCell.toggle(FoldingCell.java:224)
                                                                                  at sinadalvand.a30nama.co.a30nama.Recycle.PostPageRecycleAdapter$DownloadHolder$3.onItemClick(PostPageRecycleAdapter.java:134)`

i use this list view in Recycle view when i touch card i receive this error .

what is this meaning?

**Comment by anubhavmalik** [comment]
+1

**Comment by Eun0** [comment]
+2

**Comment by anubhavmalik** [comment]
Solution : i played around with the flipcount attrib in xml and it worked for me, essentially the flipcount decides how many flips there have to be to unfold your card, you can either increase the height of your card or change the flip count and try to get a count for which your app doesnt crash..

**Comment by jules2m1998** [comment]
Thank it helped me

**Comment by jules2m1998** [comment]
> Solution: j'ai joué avec l'attribut flipcount au format xml et cela a fonctionné pour moi. Essentiellement, le flipcount décide du nombre de retournements nécessaires pour déplier votre carte. Vous pouvez augmenter la hauteur de votre carte ou modifier le nombre de retournements et essayer de le faire. Obtenez un compte pour lequel votre application ne plante pas ..

thank you it helped me

**Comment by Abhishek06042000** [comment]
> Solution : i played around with the flipcount attrib in xml and it worked for me, essentially the flipcount decides how many flips there have to be to unfold your card, you can either increase the height of your card or change the flip count and try to get a count for which your app doesnt crash..

Thank you it helped me

**Comment by qadeerhm92** [comment]
If you don't want folding animation foldingCell.toggle(true);
